camera:
  device_index: 0
  resolution: [640, 480]
  fps: 25
  reconnect_delay_ms: 2000

yolo:
  weights_path: "../weights/brown-egg.pt"
  confidence_threshold: 0.7
  iou_threshold: 0.5
  device: "cpu"
  max_det: 50

logging:
  level: "INFO"
  filepath: "../logs/app.log"
  max_bytes: 5242880
  backup_count: 5
  console: true

app:
  enable_overlay: true
  roi:
    top_left: [0.1, 0.1]
    bottom_right: [0.9, 0.9]

control:
  serial:
    port: "COM14"
    baudrate: 115200
    ack_timeout_ms: 700
    response_timeout_ms: 1200
    max_retries: 3
  scheduler:
    actor_status_interval_ms: 1000
    arm_status_interval_ms: 1000
    scan_only_timeout_ms: 5000
    move_only_duration_ms: 5000
    detection_refresh_interval_ms: 1000
    turn_check_interval_ms: 1000
  behaviour:
    distance_stop_threshold_cm: 30.0
    detection_center_tolerance: 0.2
    detection_min_confidence: 0.6
    max_arm_pick_attempts: 3
    arm_ready_timeout_ms: 2000
    arm_pick_timeout_ms: 8000
